/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OurProcessRouteImport } from './routes/our-process'
import { Route as PersonalizedGiftsRouteImport } from './routes/personalized-gifts'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductsSlugPersonalizeRouteImport } from './routes/products.$slug.personalize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OurProcessRoute = OurProcessRouteImport.update({
  id: '/our-process',
  path: '/our-process',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizedGiftsRoute = PersonalizedGiftsRouteImport.update({
  id: '/personalized-gifts',
  path: '/personalized-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugPersonalizeRoute = ProductsSlugPersonalizeRouteImport.update({
  id: '/personalize',
  path: '/personalize',
  getParentRoute: () => ProductsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/discounts': typeof DiscountsRoute
  '/faq': typeof FaqRoute
  '/our-process': typeof OurProcessRoute
  '/personalized-gifts': typeof PersonalizedGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/personalize': typeof ProductsSlugPersonalizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/discounts': typeof DiscountsRoute
  '/faq': typeof FaqRoute
  '/our-process': typeof OurProcessRoute
  '/personalized-gifts': typeof PersonalizedGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/collections': typeof CollectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$slug/personalize': typeof ProductsSlugPersonalizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/discounts': typeof DiscountsRoute
  '/faq': typeof FaqRoute
  '/our-process': typeof OurProcessRoute
  '/personalized-gifts': typeof PersonalizedGiftsRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/personalize': typeof ProductsSlugPersonalizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/b2b'
    | '/cart'
    | '/cookies'
    | '/discounts'
    | '/faq'
    | '/our-process'
    | '/personalized-gifts'
    | '/privacy'
    | '/returns'
    | '/terms'
    | '/collections/$slug'
    | '/products/$slug'
    | '/collections/'
    | '/products/'
    | '/products/$slug/personalize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/b2b'
    | '/cart'
    | '/cookies'
    | '/discounts'
    | '/faq'
    | '/our-process'
    | '/personalized-gifts'
    | '/privacy'
    | '/returns'
    | '/terms'
    | '/collections/$slug'
    | '/products/$slug'
    | '/collections'
    | '/products'
    | '/products/$slug/personalize'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/b2b'
    | '/cart'
    | '/cookies'
    | '/discounts'
    | '/faq'
    | '/our-process'
    | '/personalized-gifts'
    | '/privacy'
    | '/returns'
    | '/terms'
    | '/collections/$slug'
    | '/products/$slug'
    | '/collections/'
    | '/products/'
    | '/products/$slug/personalize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  B2bRoute: typeof B2bRoute
  CartRoute: typeof CartRoute
  CookiesRoute: typeof CookiesRoute
  DiscountsRoute: typeof DiscountsRoute
  FaqRoute: typeof FaqRoute
  OurProcessRoute: typeof OurProcessRoute
  PersonalizedGiftsRoute: typeof PersonalizedGiftsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  TermsRoute: typeof TermsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-process': {
      id: '/our-process'
      path: '/our-process'
      fullPath: '/our-process'
      preLoaderRoute: typeof OurProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalized-gifts': {
      id: '/personalized-gifts'
      path: '/personalized-gifts'
      fullPath: '/personalized-gifts'
      preLoaderRoute: typeof PersonalizedGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug/personalize': {
      id: '/products/$slug/personalize'
      path: '/personalize'
      fullPath: '/products/$slug/personalize'
      preLoaderRoute: typeof ProductsSlugPersonalizeRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
  }
}

interface ProductsSlugRouteChildren {
  ProductsSlugPersonalizeRoute: typeof ProductsSlugPersonalizeRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugPersonalizeRoute: ProductsSlugPersonalizeRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  B2bRoute: B2bRoute,
  CartRoute: CartRoute,
  CookiesRoute: CookiesRoute,
  DiscountsRoute: DiscountsRoute,
  FaqRoute: FaqRoute,
  OurProcessRoute: OurProcessRoute,
  PersonalizedGiftsRoute: PersonalizedGiftsRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  TermsRoute: TermsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
