// Generated by scripts/generate-api-schema.mjs. Do not edit manually.

export interface AdjustInventoryRequest {
  "low_stock_threshold"?: unknown
  "quantity_delta": number
  "reason": string
}

export interface AssignCategoriesRequest {
  "category_ids": Array<string>
}

export interface Category {
  "description": string
  "id": string
  "name": string
  "slug": string
}

export interface ChangeProductStatusRequest {
  "status": string
}

export interface CompleteUploadRequest {
  "alt_text": string
  "product_id": string
}

export interface CreateAccountAddressRequest {
  "address_type": string
  "city": string
  "country_code": string
  "line1": string
  "line2"?: string
  "phone"?: string
  "postal_code": string
  "recipient_name": string
  "region"?: string
}

export interface CreateCategoryRequest {
  "description"?: string
  "name": string
  "slug": string
}

export interface CreateProductRequest {
  "description"?: string
  "search_keywords"?: string
  "slug": string
  "title": string
  "variants": Array<CreateVariantRequest>
}

export interface CreateStaffRequest {
  "capabilities"?: Array<string>
  "display_name": string
  "email": string
  "password": string
}

export interface CreateVariantRequest {
  "currency": string
  "option_values"?: unknown
  "price_minor": number
  "sku": string
  "title": string
}

export interface CustomerAccountProfile {
  "addresses": Array<CustomerAddress>
  "email": string
  "first_name": string
  "id": string
  "last_name": string
  "phone": string
}

export interface CustomerAddress {
  "address_type": string
  "city": string
  "country_code": string
  "id": string
  "line1": string
  "line2": string
  "phone": string
  "postal_code": string
  "recipient_name": string
  "region": string
}

export interface CustomerAddressInput {
  "city": string
  "country_code": string
  "line1": string
  "line2"?: string
  "phone"?: string
  "postal_code": string
  "recipient_name": string
  "region"?: string
}

export interface CustomerDetail {
  "addresses": Array<CustomerAddress>
  "created_at": string
  "customer_type": string
  "email": string
  "first_name": string
  "id": string
  "last_name": string
  "order_count": number
  "phone": string
  "retention_expires_at": string
}

export interface CustomerLoginRequest {
  "email": string
  "password": string
}

export interface CustomerRegisterRequest {
  "email": string
  "first_name": string
  "last_name": string
  "password": string
  "phone"?: string
}

export interface CustomerSummary {
  "address_count": number
  "created_at": string
  "customer_type": string
  "email": string
  "first_name": string
  "id": string
  "last_name": string
}

export interface DisableStaffRequest {
  "reason": string
}

export interface ErrorBody {
  "error": ErrorDetail
}

export interface ErrorDetail {
  "code": string
  "message": string
}

export interface GuestCustomerReceipt {
  "address_id": string
  "customer_id": string
}

export interface GuestCustomerRequest {
  "address": CustomerAddressInput
  "email": string
  "first_name": string
  "last_name": string
  "phone"?: string
}

export interface Health {
  "service": string
  "status": string
}

export interface InitiateUploadRequest {
  "byte_size": number
  "content_type": string
  "filename": string
}

export interface InitiateUploadResponse {
  "expires_in_seconds": number
  "id": string
  "method": string
  "upload_url": string
}

export interface InventoryMovement {
  "actor_display_name"?: unknown
  "created_at": string
  "id": string
  "movement_type": string
  "quantity_delta": number
  "reason": string
  "resulting_available_quantity": number
  "variant_id": string
}

export interface InventoryRecord {
  "available_quantity": number
  "committed_quantity": number
  "low_stock": boolean
  "low_stock_threshold": number
  "product_id": string
  "product_title": string
  "reserved_quantity": number
  "sku": string
  "variant_id": string
  "variant_title": string
}

export interface LoginRequest {
  "email": string
  "password": string
}

export interface MediaRecord {
  "alt_text": string
  "id": string
  "position": number
  "product_id": string
}

export interface Product {
  "categories": Array<Category>
  "description": string
  "id": string
  "media": Array<ProductMedia>
  "search_keywords": string
  "slug": string
  "status": string
  "title": string
  "variants": Array<Variant>
}

export interface ProductMedia {
  "alt_text": string
  "card_url": string
  "detail_url": string
  "id": string
  "position": number
  "thumbnail_url": string
  "url": string
}

export interface StaffProfile {
  "capabilities": Array<string>
  "display_name": string
  "email": string
  "id": string
  "role": string
}

export interface StaffRecord {
  "capabilities": Array<string>
  "disabled": boolean
  "display_name": string
  "email": string
  "id": string
  "role": string
}

export interface Variant {
  "available_quantity": number
  "currency": string
  "id": string
  "low_stock": boolean
  "option_values": unknown
  "position": number
  "price_minor": number
  "sku": string
  "title": string
}
