// Generated by scripts/generate-api-schema.mjs. Do not edit manually.

export interface AccountTokenRequest {
  "token": string
}

export interface AddCartItemRequest {
  "customization"?: unknown
  "customization_media_asset_id"?: string | null
  "customization_media_asset_ids"?: Array<string>
  "quantity": number
  "variant_id": string
}

export interface AdjustInventoryRequest {
  "low_stock_threshold"?: number | null
  "quantity_delta": number
  "reason": string
}

export interface AdminProductFeedback {
  "comment": string
  "created_at": string
  "display_name": string
  "id": string
  "moderated_at"?: string | null
  "moderated_by_name"?: string | null
  "product_id": string
  "product_slug": string
  "product_title": string
  "rating": number
  "replied_at"?: string | null
  "replied_by_name"?: string | null
  "status": string
  "store_reply"?: string | null
}

export interface AppliedDiscount {
  "amount_minor": number
  "code": string
  "kind": string
}

export interface ApplyDiscountRequest {
  "code": string
}

export interface AssignCategoriesRequest {
  "category_ids": Array<string>
}

export interface CancelOrderRequest {
  "internal_note"?: string
  "reason": string
}

export interface Cart {
  "checkout_ready": boolean
  "currency"?: string | null
  "delivery"?: null | CartDelivery
  "discount"?: null | AppliedDiscount
  "discount_minor": number
  "expires_at": string
  "id": string
  "issues": Array<CartIssue>
  "item_count": number
  "items": Array<CartItem>
  "shipping"?: null | ShippingSelection
  "shipping_methods": Array<ShippingSelection>
  "shipping_minor": number
  "subtotal_minor": number
  "tax"?: null | TaxSelection
  "tax_minor": number
  "total_minor": number
}

export interface CartAddress {
  "city": string
  "country_code": string
  "line1": string
  "line2": string
  "phone": string
  "postal_code": string
  "recipient_name": string
  "region": string
}

export interface CartDelivery {
  "address": CartAddress
  "address_id": string
  "customer_id": string
  "email": string
  "first_name": string
  "last_name": string
  "phone": string
}

export interface CartIssue {
  "code": string
  "line_id"?: string | null
  "message": string
}

export interface CartItem {
  "available": boolean
  "available_quantity": number
  "currency": string
  "customization"?: unknown
  "customization_media_asset_id"?: string | null
  "customization_media_asset_ids": Array<string>
  "id": string
  "image_url"?: string | null
  "line_total_minor": number
  "product_slug": string
  "product_title": string
  "quantity": number
  "sku": string
  "unit_price_minor": number
  "variant_id": string
  "variant_title": string
}

export interface Category {
  "description": string
  "id": string
  "name": string
  "position": number
  "slug": string
}

export interface ChangeDiscountStatusRequest {
  "enabled": boolean
  "reason": string
}

export interface ChangeProductStatusRequest {
  "status": string
}

export interface CommercialSettings {
  "currency": string
  "history": Array<SettingsHistoryRecord>
  "integrations": IntegrationHealth
  "shipping_zones": Array<ShippingZone>
  "store_name": string
  "support_email": string
  "tax_automation": TaxAutomationStatus
  "tax_enabled": boolean
  "tax_rules": Array<TaxRule>
  "updated_at": string
}

export interface CompleteUploadRequest {
  "alt_text": string
  "product_id": string
}

export interface CreateAccountAddressRequest {
  "address_type": string
  "city": string
  "country_code": string
  "line1": string
  "line2"?: string
  "phone"?: string
  "postal_code": string
  "recipient_name": string
  "region"?: string
}

export interface CreateCategoryRequest {
  "description"?: string
  "name": string
  "slug": string
}

export interface CreateDiscountRequest {
  "code": string
  "currency": string
  "ends_at"?: string | null
  "kind": string
  "minimum_order_minor"?: number
  "per_customer_limit"?: number | null
  "reason": string
  "starts_at"?: string | null
  "usage_limit"?: number | null
  "value": number
}

export interface CreateFulfillmentLineRequest {
  "order_line_id": string
  "quantity": number
}

export interface CreateFulfillmentRequest {
  "carrier": string
  "lines": Array<CreateFulfillmentLineRequest>
  "reason": string
  "tracking_number": string
  "tracking_url": string
}

export interface CreateOrderRequest {
  "payment_method": string
}

export interface CreateProductFeedbackRequest {
  "comment": string
  "display_name": string
  "rating": number
}

export interface CreateProductRequest {
  "additional_information"?: string
  "care_instructions"?: string
  "description"?: string
  "personalization"?: PersonalizationConfig
  "search_keywords"?: string
  "shipping"?: ShippingProfile
  "slug": string
  "title": string
  "variants": Array<CreateVariantRequest>
}

export interface CreateRefundLineRequest {
  "order_line_id": string
  "quantity": number
}

export interface CreateRefundRequest {
  "internal_note"?: string
  "lines"?: Array<CreateRefundLineRequest>
  "mode": string
  "reason": string
  "restock": boolean
}

export interface CreateStaffRequest {
  "capabilities"?: Array<string>
  "display_name": string
  "email": string
  "password": string
}

export interface CreateVariantRequest {
  "available_quantity"?: number
  "currency": string
  "option_values"?: unknown
  "price_minor": number
  "sku": string
  "title": string
}

export interface CustomerAccountProfile {
  "addresses": Array<CustomerAddress>
  "email": string
  "email_verified": boolean
  "first_name": string
  "id": string
  "last_name": string
  "phone": string
}

export interface CustomerAddress {
  "address_type": string
  "city": string
  "country_code": string
  "id": string
  "line1": string
  "line2": string
  "phone": string
  "postal_code": string
  "recipient_name": string
  "region": string
}

export interface CustomerAddressInput {
  "city": string
  "country_code": string
  "line1": string
  "line2"?: string
  "phone"?: string
  "postal_code": string
  "recipient_name": string
  "region"?: string
}

export interface CustomerDetail {
  "addresses": Array<CustomerAddress>
  "created_at": string
  "customer_type": string
  "email": string
  "first_name": string
  "id": string
  "last_name": string
  "order_count": number
  "phone": string
  "retention_expires_at": string
}

export interface CustomerLoginRequest {
  "email": string
  "password": string
}

export interface CustomerRegisterRequest {
  "email": string
  "first_name": string
  "last_name": string
  "password": string
  "phone"?: string
}

export interface CustomerSummary {
  "address_count": number
  "created_at": string
  "customer_type": string
  "email": string
  "first_name": string
  "id": string
  "last_name": string
}

export interface DashboardAccess {
  "inventory": boolean
  "orders": boolean
  "settings": boolean
}

export interface DashboardFailedPayment {
  "amount_minor": number
  "currency": string
  "customer_name": string
  "failure_message": string
  "order_id": string
  "order_number": string
  "updated_at": string
}

export interface DashboardInventory {
  "available_quantity": number
  "low_stock_threshold": number
  "product_title": string
  "sku": string
  "variant_id": string
  "variant_title": string
}

export interface DashboardMetrics {
  "failed_payments"?: number | null
  "gross_revenue_minor"?: number | null
  "low_stock_variants"?: number | null
  "net_revenue_minor"?: number | null
  "orders_today"?: number | null
  "orders_total"?: number | null
  "paid_awaiting_fulfillment"?: number | null
  "refunds_minor"?: number | null
}

export interface DashboardOrder {
  "created_at": string
  "currency": string
  "customer_name": string
  "fulfillment_status": string
  "id": string
  "order_number": string
  "payment_status": string
  "total_minor": number
}

export interface DashboardRefund {
  "amount_minor": number
  "created_at": string
  "currency": string
  "id": string
  "order_id": string
  "order_number": string
  "reason": string
  "status": string
}

export interface DisableStaffRequest {
  "reason": string
}

export interface Discount {
  "code": string
  "created_at": string
  "currency": string
  "ends_at"?: string | null
  "id": string
  "kind": string
  "minimum_order_minor": number
  "per_customer_limit"?: number | null
  "starts_at"?: string | null
  "status": string
  "usage_count": number
  "usage_limit"?: number | null
  "value": number
}

export interface ErrorBody {
  "error": ErrorDetail
}

export interface ErrorDetail {
  "code": string
  "message": string
}

export interface ForgotPasswordRequest {
  "email": string
}

export interface Fulfillment {
  "actor_display_name"?: string | null
  "carrier": string
  "created_at": string
  "id": string
  "lines": Array<FulfillmentLine>
  "reason": string
  "tracking_number": string
  "tracking_url": string
}

export interface FulfillmentLine {
  "order_line_id": string
  "product_title": string
  "quantity": number
  "sku": string
  "variant_title": string
}

export interface GuestCustomerReceipt {
  "address_id": string
  "customer_id": string
}

export interface GuestCustomerRequest {
  "address": CustomerAddressInput
  "email": string
  "first_name": string
  "last_name": string
  "phone"?: string
}

export interface Health {
  "service": string
  "status": string
}

export interface InitiateUploadRequest {
  "byte_size": number
  "content_type": string
  "filename": string
}

export interface InitiateUploadResponse {
  "expires_in_seconds": number
  "id": string
  "method": string
  "upload_url": string
}

export interface IntegrationHealth {
  "database": string
  "email": string
  "media_storage": string
  "packlink": PacklinkConfigurationStatus
  "payments": string
}

export interface InventoryMovement {
  "actor_display_name"?: string | null
  "created_at": string
  "id": string
  "movement_type": string
  "quantity_delta": number
  "reason": string
  "resulting_available_quantity": number
  "variant_id": string
}

export interface InventoryRecord {
  "available_quantity": number
  "committed_quantity": number
  "low_stock": boolean
  "low_stock_threshold": number
  "product_id": string
  "product_title": string
  "reserved_quantity": number
  "sku": string
  "variant_id": string
  "variant_title": string
}

export interface LoginRequest {
  "email": string
  "password": string
}

export interface ManualPaymentRequest {
  "reason": string
}

export interface MediaRecord {
  "alt_text": string
  "id": string
  "position": number
  "product_id": string
}

export interface MetricDefinition {
  "description": string
  "key": string
}

export interface ModerateProductFeedbackRequest {
  "status": string
}

export interface NotificationStatus {
  "attempt_count": number
  "created_at": string
  "id": string
  "kind": string
  "last_error"?: string | null
  "sent_at"?: string | null
  "status": string
}

export interface OperationalDashboard {
  "access": DashboardAccess
  "currency": string
  "definitions": Array<MetricDefinition>
  "failed_payments": Array<DashboardFailedPayment>
  "generated_at": string
  "low_stock_variants": Array<DashboardInventory>
  "metrics": DashboardMetrics
  "paid_awaiting_fulfillment": Array<DashboardOrder>
  "period_start": string
  "recent_orders": Array<DashboardOrder>
  "recent_refunds": Array<DashboardRefund>
  "tax_automation"?: null | TaxAutomationStatus
  "timezone": string
}

export interface Order {
  "created_at": string
  "currency": string
  "customer": OrderCustomer
  "discount"?: null | OrderDiscount
  "discount_minor": number
  "fulfillment_status": string
  "fulfillments": Array<Fulfillment>
  "id": string
  "lines": Array<OrderLine>
  "notifications": Array<NotificationStatus>
  "operations": OrderOperations
  "order_number": string
  "order_status": string
  "payment": OrderPayment
  "payment_status": string
  "refunds": Array<Refund>
  "shipping": OrderShipping
  "shipping_address": OrderAddress
  "shipping_minor": number
  "subtotal_minor": number
  "tax": OrderTax
  "tax_minor": number
  "timeline": Array<OrderEvent>
  "total_minor": number
}

export interface OrderAddress {
  "city": string
  "country_code": string
  "line1": string
  "line2": string
  "phone": string
  "postal_code": string
  "recipient_name": string
  "region": string
}

export interface OrderCustomer {
  "email": string
  "first_name": string
  "last_name": string
  "phone": string
}

export interface OrderDiscount {
  "amount_minor": number
  "code": string
  "currency": string
  "kind": string
  "value": number
}

export interface OrderEvent {
  "actor_display_name"?: string | null
  "created_at": string
  "detail": string
  "event_type": string
  "id": string
  "title": string
}

export interface OrderLine {
  "currency": string
  "customization"?: unknown
  "customization_media_asset_id"?: string | null
  "customization_media_asset_ids": Array<string>
  "fulfilled_quantity": number
  "id": string
  "line_total_minor": number
  "personalization_context"?: unknown
  "product_title": string
  "quantity": number
  "sku": string
  "unit_price_minor": number
  "variant_title": string
}

export interface OrderOperations {
  "can_cancel": boolean
  "can_refund": boolean
  "cancel_unavailable_reason"?: string | null
  "refund_unavailable_reason"?: string | null
  "refundable_minor": number
}

export interface OrderPayment {
  "amount_minor": number
  "attempts": Array<PaymentAttempt>
  "currency": string
  "failure_code"?: string | null
  "failure_message"?: string | null
  "history": Array<PaymentStatusEvent>
  "paid_at"?: string | null
  "provider": string
  "status": string
}

export interface OrderShipping {
  "amount_minor": number
  "carrier_name": string
  "country_code": string
  "currency": string
  "departure_dropoff": boolean
  "destination_dropoff": boolean
  "external_service_id": string
  "method_name": string
  "provider": string
  "transit_hours": number
  "zone_name": string
}

export interface OrderSummary {
  "created_at": string
  "currency": string
  "customer_email": string
  "customer_name": string
  "fulfillment_status": string
  "id": string
  "item_count": number
  "order_number": string
  "order_status": string
  "payment_status": string
  "total_minor": number
}

export interface OrderTax {
  "amount_minor": number
  "behavior": string
  "country_code": string
  "rate_basis_points": number
  "rule_name": string
  "taxable_amount_minor": number
}

export interface PacklinkConfigurationStatus {
  "origin": string
  "package": string
  "status": string
}

export interface PaymentAttempt {
  "attempt_number": number
  "created_at": string
  "expires_at"?: string | null
  "failure_code"?: string | null
  "failure_message"?: string | null
  "id": string
  "provider": string
  "status": string
}

export interface PaymentCheckout {
  "checkout_url": string
  "expires_at": string
  "order_id": string
  "provider": string
}

export interface PaymentOptions {
  "manual": boolean
  "stripe": boolean
}

export interface PaymentStatusEvent {
  "created_at": string
  "detail": string
  "event_type": string
  "id": string
  "provider_status": string
}

export interface PersonalizationConfig {
  "allowed_colors": unknown
  "allowed_fonts": unknown
  "area_height": number
  "area_width": number
  "area_x": number
  "area_y": number
  "mode": string
  "preview_media_id"?: string | null
  "print_areas"?: unknown
  "text_area_height": number
  "text_area_width": number
  "text_area_x": number
  "text_area_y": number
  "text_max_characters": number
  "text_max_size": number
  "text_min_size": number
  "views"?: unknown
}

export interface PersonalizationMediaRecord {
  "id": string
  "preview_url": string
}

export interface Product {
  "additional_information": string
  "care_instructions": string
  "categories": Array<Category>
  "description": string
  "id": string
  "media": Array<ProductMedia>
  "personalization": PersonalizationConfig
  "search_keywords": string
  "shipping": ShippingProfile
  "slug": string
  "status": string
  "title": string
  "variants": Array<Variant>
}

export interface ProductFeedback {
  "comment": string
  "created_at": string
  "display_name": string
  "id": string
  "rating": number
  "replied_at"?: string | null
  "store_reply"?: string | null
}

export interface ProductFeedbackSummary {
  "average_rating"?: number | null
  "rating_counts": Array<RatingCount>
  "reviews": Array<ProductFeedback>
  "total_reviews": number
}

export interface ProductMedia {
  "alt_text": string
  "card_url": string
  "detail_url": string
  "id": string
  "position": number
  "thumbnail_url": string
  "url": string
}

export interface RatingCount {
  "count": number
  "rating": number
}

export interface Refund {
  "actor_display_name"?: string | null
  "amount_minor": number
  "completed_at"?: string | null
  "created_at": string
  "currency": string
  "failure_code"?: string | null
  "failure_message"?: string | null
  "id": string
  "internal_note"?: string | null
  "lines": Array<RefundLine>
  "mode": string
  "provider": string
  "provider_refund_id"?: string | null
  "reason": string
  "restock": boolean
  "status": string
}

export interface RefundLine {
  "amount_minor": number
  "order_line_id": string
  "product_title": string
  "quantity": number
  "sku": string
  "variant_title": string
}

export interface ReorderCategoriesRequest {
  "category_ids": Array<string>
}

export interface ReplyToProductFeedbackRequest {
  "reply"?: string | null
}

export interface ResetPasswordRequest {
  "password": string
  "token": string
}

export interface SelectShippingMethodRequest {
  "shipping_method_id": string
}

export interface SettingsHistoryRecord {
  "actor_display_name"?: string | null
  "created_at": string
  "id": string
  "reason": string
}

export interface ShippingMethod {
  "active": boolean
  "currency": string
  "flat_rate_minor": number
  "id": string
  "name": string
}

export interface ShippingMethodInput {
  "active": boolean
  "flat_rate_minor": number
  "name": string
}

export interface ShippingPackageProfile {
  "active": boolean
  "empty_weight_grams": number
  "height_cm": number
  "id": string
  "length_cm": number
  "name": string
  "width_cm": number
}

export interface ShippingPackageProfileRequest {
  "active"?: boolean
  "empty_weight_grams"?: number
  "height_cm": number
  "length_cm": number
  "name": string
  "width_cm": number
}

export interface ShippingProfile {
  "configured": boolean
  "empty_weight_grams"?: number
  "height_cm": number
  "length_cm": number
  "package_profile_id"?: string | null
  "package_profile_name"?: string | null
  "units_per_package": number
  "weight_grams": number
  "width_cm": number
}

export interface ShippingSelection {
  "amount_minor": number
  "carrier_name": string
  "currency": string
  "departure_dropoff": boolean
  "destination_dropoff": boolean
  "id": string
  "method_name": string
  "provider": string
  "service_id": string
  "transit_hours": number
  "zone_name": string
}

export interface ShippingZone {
  "active": boolean
  "country_codes": Array<string>
  "id": string
  "methods": Array<ShippingMethod>
  "name": string
}

export interface ShippingZoneInput {
  "active": boolean
  "country_codes": Array<string>
  "methods": Array<ShippingMethodInput>
  "name": string
}

export interface StaffProfile {
  "capabilities": Array<string>
  "display_name": string
  "email": string
  "id": string
  "role": string
}

export interface StaffRecord {
  "capabilities": Array<string>
  "disabled": boolean
  "display_name": string
  "email": string
  "id": string
  "role": string
}

export interface SubmittedProductFeedback {
  "id": string
  "status": string
}

export interface TaxAutomationStatus {
  "activated_at"?: string | null
  "activation_reason"?: string | null
  "enabled": boolean
  "immediate_threshold_minor": number
  "remaining_to_immediate_minor": number
  "remaining_to_standard_minor": number
  "standard_threshold_minor": number
  "state": string
  "turnover_minor": number
  "warning_threshold_minor": number
  "year": number
}

export interface TaxRule {
  "active": boolean
  "country_codes": Array<string>
  "id": string
  "name": string
  "rate_basis_points": number
}

export interface TaxRuleInput {
  "active": boolean
  "country_codes": Array<string>
  "name": string
  "rate_basis_points": number
}

export interface TaxSelection {
  "amount_minor": number
  "behavior": string
  "rate_basis_points": number
  "rule_name": string
  "taxable_amount_minor": number
}

export interface UpdateCartItemRequest {
  "quantity": number
}

export interface UpdateCommercialSettingsRequest {
  "currency": string
  "reason": string
  "shipping_zones": Array<ShippingZoneInput>
  "store_name": string
  "support_email": string
  "tax_enabled": boolean
  "tax_rules": Array<TaxRuleInput>
}

export interface UpdateDiscountRequest {
  "code": string
  "currency": string
  "ends_at"?: string | null
  "kind": string
  "minimum_order_minor"?: number
  "per_customer_limit"?: number | null
  "reason": string
  "starts_at"?: string | null
  "usage_limit"?: number | null
  "value": number
}

export interface UpdateProductRequest {
  "additional_information"?: string
  "available_quantity": number
  "care_instructions"?: string
  "currency": string
  "description"?: string
  "personalization"?: PersonalizationConfig
  "price_minor": number
  "search_keywords"?: string
  "shipping"?: ShippingProfile
  "sku": string
  "slug": string
  "title": string
}

export interface Variant {
  "available_quantity": number
  "currency": string
  "display_price_minor": number
  "display_tax_rate_basis_points": number
  "id": string
  "low_stock": boolean
  "option_values": unknown
  "position": number
  "price_minor": number
  "sku": string
  "title": string
}
